### ISSUE TITLE
PRIORITY Find bug that crashes site

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#101]
I cannot do any further code changes or release the `/rfc` part until we can get the site to stop crashing.  Please add any logging or checkers necessary to find the root issue.

**Comment by glozhkovoy** [comment]
I spent a few time for investigate the problem. 

I have two ideas:
* It's cache. Cache takes to much memory and node fails.
I will make a step back and step forward to check this: rewrite api's without caching and cover #76. After all add caching for queries by redis server.
* Wepback fails for some reason.
Maybe start app with wepback isn't good solution. After build webpack create fully working site in dest folder. I will try to server this files over nodemon.

This is my flow to find the reason. Now it's clear for you. 

Thanks.

**Comment by glozhkovoy** [comment]
Please check and deliver this PR -- https://github.com/data-skeptic/dataskeptic.com/pull/109

**Comment by kylepolich** [comment]
I think this one is finally resolved!
