### ISSUE TITLE
Expose APIs for chat bot

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#156]
We are going to be introducing a chatbot.  It will be a 100% stand alone service running on a separate EC2 instance.  The website will make it available using an iframe as described in #154 .

The bot is going to help the user pick out an episode to listen to.  Then it will ask the user "Would you like me to play that for you?"  When user types "yes", the BOT wants to make a call to let dataskeptic.com know to play this track in the current browser which contains the iframe.

Is it possible?

I want the same option to have the Bot add something to the shopping cart also.

What is the best implementation?

**Comment by glozhkovoy** [comment]
Is it possible to handle `yes` action and call some js code like `alert`, `console.log`, e.t.c in iframe(bot)?

**Comment by kylepolich** [comment]
Yes, the wrapper code for the bot runs in Node.  If a regular iframe can execute `alert` then so can bot.  If I do `console.log`, however, the message will appear in the logs of the server running the bot code.

I think either the bot needs to communicate "directly" with the site via javascript.  Or the bot needs to call `dataskeptic.com/api/whatever`.  In the second case, how can we tell the site which user we are talking about?

**Comment by glozhkovoy** [comment]
Ok.

There is a browser/JavaScript feature — https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage. It’s like streams on Unix. 

You can send message from iframe and dataskeptic page could handle it.

From your side code completely easy, like ‘postMessage(“blablabla”)’

**Comment by kylepolich** [comment]
Can you provide more of an example?

**Comment by kylepolich** [comment]
@glozhkovoy

**Comment by glozhkovoy** [comment]
Sorry for waiting.
Here is the small example: 
I made a simple web page with js script and created separate http server, that has the  button, when you click the  button  it sends to parent (dataskeptic.com) message: 
```
parent.postMessage({
    status: true,
    message: 'Hi! This is chat bot!'
}, '*')
```

And in App Container I created an event listener for this message
```
componentWillMount() {
        window.addEventListener("message", this.listenMessage);
}

listenMessage(e) {
        if (this.validateOrigin(e))
            alert(`Status: ${e.data.status} \nMessage: ${e.data.message}`)
}
```

So you can send data from chat bot via post message,  for example: 
```
type: "podcast" 
id: "id" 
```
I will get this information inside App and can redirect user to podcast.


Example gif (iframe is on localhost:5000 and dataskeptic on localhost:3000)
![cl918tczmr](https://user-images.githubusercontent.com/20016615/29312729-61f1184c-81bf-11e7-9b02-c681cddedca6.gif)

**Comment by kylepolich** [comment]
@glozhkovoy This looks like a great approach, but I am having trouble getting it working.

The bot is running node.js code.  When I try to use `parent` I get `ReferenceError: parent is not defined`.  Is there something special to do in node.js to get the parent object?

**Comment by kylepolich** [comment]
I don't know if it would be helpful, but you can go to the bot live in prod and try the test by saying `test-msg`

<img width="325" alt="screen shot 2017-09-13 at 9 16 57 pm" src="https://user-images.githubusercontent.com/1054674/30411895-f6efe3fe-98c8-11e7-9af4-a8cf46977d12.png">

**Comment by kylepolich** [comment]
![screen shot 2017-09-13 at 9 18 05 pm](https://user-images.githubusercontent.com/1054674/30411915-10a0630a-98c9-11e7-8ee8-532795d992a5.png)

**Comment by kylepolich** [comment]
@glozhkovoy any update?
