### ISSUE TITLE
Blog landing error

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#157]
Very often, when I pull up the URL for a podcast episode, the player is NOT present.  If I refresh, the player shows up immediately.  If I close the tab and visit again, the player is there.  It seems to only happen on the very first look at the page.  However, this is very bad, since most users will not know to hit refresh.

Example (might be reproducible for you):

https://dataskeptic.com/blog/episodes/2017/pix2code

Visit it.  Is the player at the top?  Probably not.  Hit refresh.  Now it is there.  Why?

**Comment by glozhkovoy** [comment]
Reproducible
