### ISSUE TITLE
URGENT: Admin has been broken

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#170]
The admin branch has somehow been changed to always run in dev mode, even when I do `npm run start` and I get this print out:

```
---[Refreshing cache]------------------
{ rss: 269438976, heapTotal: 245604352, heapUsed: 202169176 }
Server listening on 3000
'env = prod'
```

When running in prod mode, it is supposed to use a different Stripe key to retrieve real orders.  Right now it's only showing dev orders.  This is blocking us from fulfilling the orders.

**Comment by glozhkovoy** [comment]
We definitely should have an debug session to catch this issue

**Comment by kylepolich** [comment]
I may have found the issue.  Will update soon.

**Comment by kylepolich** [comment]
This was my mistake.  I forgot that when trying to make it work, we over-wrote the config file with one provided by @glozhkovoy .  I merged my config to yours to get it working.  Fixed now.
