### ISSUE TITLE
Confirmation UI for /rfc

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#203]
Today, we have this nice result:

![screen shot 2017-08-28 at 9 47 49 pm](https://user-images.githubusercontent.com/1054674/29804860-9f960ec0-8c3a-11e7-8e17-90a999fa5063.png)

Let's make these changes:

- [x] "Thank you for proposal!" -> "Your recording has been successfully uploaded.  Thanks for sharing your thoughts!"

- [x] Hide the play button

- [x] Hide "Discard and record again" button

- [x] Provide a link that says "Record another submission" which resets the process

**Comment by glozhkovoy** [comment]
Improved server error catching on submit action.

![mgggqjx6bb](https://user-images.githubusercontent.com/20016615/30001360-9a0c6e28-9094-11e7-80bd-c84169abbe63.gif)

**Comment by kylepolich** [comment]
Nice work.
