### ISSUE TITLE
HTTPS issue with recordingServer?

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#204]
I deployed the latest code to production tonight.  You can test it live.

I made sure that I have port 9001 open on the machine and mapped to the docker container.

The recording option is disabled saying "Server unreachable"

The developer console has this message:

`Mixed Content: The page at 'https://dataskeptic.com/rfc' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://dataskeptic.com:9001/recording'. This request has been blocked; this endpoint must be available over WSS.`

**Comment by kylepolich** [comment]
Recent improvements are better but see #206

**Comment by glozhkovoy** [comment]
Resolved.
