### ISSUE TITLE
Require login for /admin

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#207]
The router should require a login to get to /admin

Only if the user authenticates with an @dataskeptic.com address are the allowed to view the /admin page

**Comment by glozhkovoy** [comment]
Okay, but what we should use? Just simple form or Google OAuth. If we will use simple form, how we can check if this email is actually real and not some "test@datasceptic.com". 

If we will use Google OAuth, can you login with your datasceptic emails?

**Comment by kylepolich** [comment]
@glozhkovoy yes, we will use Google Oauth, this way we know it is real

**Comment by glozhkovoy** [comment]
Delivered at PR https://github.com/data-skeptic/dataskeptic.com/pull/208

**Comment by kylepolich** [comment]
Wonderful!
