### ISSUE TITLE
iTunes one click to subscribe

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#219]
Please follow these instructions:

https://busycreator.com/add-a-quick-subscribe-banner-to-your-podcast-website/

**Comment by glozhkovoy** [comment]
Works!

![img_2320](https://user-images.githubusercontent.com/20016615/30308105-90c07c30-978b-11e7-80ef-12524d89069b.jpg)

**Comment by kylepolich** [comment]
Awesome!!!!!!!
