### ISSUE TITLE
Blog cache is no longer working

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#220]
Description of animation:

- Notice on local version of site, the first sentence does not have parenthesis around LSTM.  Why not?

- I download the source file from S3 (shown here from the local filesystem).  The file I downloaded matches S3, but the result shown on the site does not match the version from S3.

- I thought maybe the site needs to be refreshed.  I do the refresh successfully.

- I try to refresh the blog, but its showing the old version.

http://g.recordit.co/l3IfYdx2dW.gif

**Comment by glozhkovoy** [comment]
Wow! Blog cache actually was filled only once.

I tested the PR with a `api/refresh` and now it's finally works as expect.

I think it's one of those JavaScript tricks.
