### ISSUE TITLE
Email html formatting error

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#227]
When I built the original admin email, somewhere I introduced `.replace("\n", "<br/>")`.  This worked for a while, but now that we have a better email system, it has become a problem:

<img width="874" alt="screen shot 2017-09-09 at 11 44 11 pm" src="https://user-images.githubusercontent.com/1054674/30246792-d4620cbc-95b8-11e7-8b2c-5467b25a1871.png">

**Comment by kylepolich** [comment]
I can work around this for now.  Not urgent.

**Comment by glozhkovoy** [comment]
Commit 0665989 should fix it. If it fixed, let's close this issue.
