### ISSUE TITLE
Reformat /podcast page to reflect new design

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#23]
Current page: https://dataskeptic.com/podcast

Updated page design: https://s3.amazonaws.com/dataskeptic-static/podcast/podcast-page.html

Note that the header is not yet updated and will be handled in another ticket.

You should implement these changes by editing ONLY these files:

https://github.com/data-skeptic/dataskeptic.com/blob/master/public/css/style.css
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Podcast.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/YearNav.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/YearSelector.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Episode.js

Note that class "center" is used throughout the site for content between header and footer.

**Comment by kelonye** [comment]
I think style.css should be split up further.

**Comment by glozhkovoy** [comment]
Hi! I'm done.

Please contact me to give access for pull-request. 

Here is examples how it looks.

<img width="1547" alt="screen shot 2017-02-11 at 10 45 22 pm" src="https://cloud.githubusercontent.com/assets/20016615/22857422/699935aa-f0ad-11e6-94fa-cb0d4cbcf668.png">
<img width="537" alt="screen shot 2017-02-11 at 10 45 17 pm" src="https://cloud.githubusercontent.com/assets/20016615/22857423/699de5e6-f0ad-11e6-93a2-61ca91626c83.png">
<img width="942" alt="screen shot 2017-02-11 at 10 45 12 pm" src="https://cloud.githubusercontent.com/assets/20016615/22857421/69991084-f0ad-11e6-9097-0efd4dab7f5f.png">

**Comment by glozhkovoy** [comment]
Delivered 
-- https://github.com/data-skeptic/dataskeptic.com/pull/34
