### ISSUE TITLE
RFC layout update

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#236]
I pushed some changes to `dev`, so start there.

We no longer have the client who is going to use RFC, so I want to make some customizations that are better for Data Skeptic.  We want to focus /rfc on audio messages only.  Let's disable comment box and upload box.  We will only have audio.  Therefore, we can remove the three boxes since it defaults to recording.

Please remove the gap at the top:

<img width="1059" alt="screen shot 2017-09-12 at 8 25 55 pm" src="https://user-images.githubusercontent.com/1054674/30359040-00fc6826-97fd-11e7-99a7-3d51c56ab5a6.png">

Let's go for this more compact layout:

![img_20170912_205537](https://user-images.githubusercontent.com/1054674/30359052-1662437a-97fd-11e7-9f5f-fbda72cdb892.jpg)

**Comment by glozhkovoy** [comment]
Hm. After the all, should we have an https://github.com/data-skeptic/dataskeptic.com/issues/198 https://github.com/data-skeptic/dataskeptic.com/issues/197? I think now it's the same.

**Comment by kylepolich** [comment]
Yes, very similar from a software perspective.  The difference is, `/questions` requires no login and will be eventually be available on Contact Us page.

Soon, we will limit who can access `/rfc` and it will be only available for certain user logins that are invited to participate.  The `/rfc` group will be prioritized and used regularly when we put the podcast together.

**Comment by kylepolich** [comment]
Let's also add another nice feature to help the users.

With a small delay (125ms) after the recording begins, have some sort of animation right next to the record button that animates in the text "Be sure to state your name and any affiliation so we can identify you on the show"  Let this message appear for 10 seconds, and then have it animate away.

If the recording length gets to 1:00, animate in the message "One minute recorded".  Hold for 5 seconds, animate off the screen.

If the recording length gets to 3:00, animate in the message "Three minute recorded.  It might be time to wrap it up.  We try to keep responses short, but if you think yours is particularly important, feel free to keep going!!".  Hold for 10 seconds, animate off the screen.

If the recording length gets to 6:00, animate in the message "Are you sure you want to be going this long?".  Hold for 5 seconds, animate off the screen.

If the recording length gets to 10:00, animate in the message "I have somewhere I need to be.  Do you think we can wrap it up?".  Hold for 5 seconds, animate off the screen.
