### ISSUE TITLE
Reformat site header to reflect new design

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#24]
All pages on dataskeptic.com have a common header.  Example page is https://dataskeptic.com/podcast

Update the header to match the designs shown here: https://s3.amazonaws.com/dataskeptic-static/podcast/podcast-page.html

You should implement these changes by editing ONLY these files:

https://github.com/data-skeptic/dataskeptic.com/blob/master/public/css/style.css
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Header.jsx
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Menu.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/NavLink.js

**Comment by glozhkovoy** [comment]
-- Delivered for desktops. https://github.com/data-skeptic/dataskeptic.com/pull/35
