### ISSUE TITLE
Implement mobile menu

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#25]
All pages on dataskeptic.com have a common header. Example page is https://dataskeptic.com/podcast

Update the header to match the designs shown here:
https://s3.amazonaws.com/dataskeptic-static/mobile/index.html#artboard6
https://s3.amazonaws.com/dataskeptic-static/mobile/index.html#artboard2

These changes are probably to be implemented in the files below.  You may need to identify other places to make changes.

https://github.com/data-skeptic/dataskeptic.com/blob/master/public/css/style.css
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Header.jsx
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Menu.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/NavLink.js

**Comment by glozhkovoy** [comment]
Hi! I'm done.

Please contact me to give access for pull-request. 

Here is examples how it looks.

<img width="1547" alt="screen shot 2017-02-11 at 10 45 22 pm" src="https://cloud.githubusercontent.com/assets/20016615/22857422/699935aa-f0ad-11e6-94fa-cb0d4cbcf668.png">
<img width="537" alt="screen shot 2017-02-11 at 10 45 17 pm" src="https://cloud.githubusercontent.com/assets/20016615/22857423/699de5e6-f0ad-11e6-93a2-61ca91626c83.png">
<img width="942" alt="screen shot 2017-02-11 at 10 45 12 pm" src="https://cloud.githubusercontent.com/assets/20016615/22857421/69991084-f0ad-11e6-9097-0efd4dab7f5f.png">

**Comment by glozhkovoy** [comment]
Implemented well-featured mobile navigation with the new mobile header template in https://github.com/data-skeptic/dataskeptic.com/pull/36

**Comment by glozhkovoy** [comment]
Delivered with PR https://github.com/data-skeptic/dataskeptic.com/pull/36.
