### ISSUE TITLE
Reformat /blog page to reflect new design

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#26]
Current page: https://dataskeptic.com/blog

Updated page design: https://s3.amazonaws.com/dataskeptic-static/blog-list/index.html

Note that the header is not yet updated and will be handled in another ticket.

You should implement these changes by editing ONLY these files:

https://github.com/data-skeptic/dataskeptic.com/blob/master/public/css/style.css
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/BlogNav.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/BlogList.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/BlogListItem.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/BlogLink.js

Note that class "center" is used throughout the site for content between header and footer.

**Comment by kylepolich** [comment]
Did you mean to close this one?  I think it still needs to be done.

**Comment by glozhkovoy** [comment]
It was mistake. Will work on it.

**Comment by glozhkovoy** [comment]
Done https://github.com/data-skeptic/dataskeptic.com/pull/70
