### ISSUE TITLE
resolve library issues

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#263]
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm WARN deprecated letsencrypt-express@2.0.6: letsencrypt-express has been renamed to greenlock-express and will now be maintained as such.
npm WARN deprecated localhost.daplie.com-certificates@1.2.5: this package has been deprecated
npm WARN deprecated letsencrypt@2.1.8: letsencrypt has been renamed to greenlock. Please find it at npm greenlock

**Comment by glozhkovoy** [comment]
Is that still reproducible? I don't see any warnings when playing with the app
