### ISSUE TITLE
Update the pull out shopping cart with different desktop/mobile approach

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#27]
Currently: 
* Visit https://dataskeptic.com/store
* Add anything to the cart
* Click the cart icon in the top menu
* Shopping cart will pop out

Update this pop out to this new design:

https://s3.amazonaws.com/dataskeptic-static/mobile/index.html#artboard9

If the user is on mobile, instead update to this design:

https://s3.amazonaws.com/dataskeptic-static/mobile/index.html#artboard0

Note that the mobile design has a fixed header and fixed footer.  When the cart has more items than can fit on the screen, the last partially visible one fades out and the middle section can be scrolled.

You should implement these changes by editing ONLY these files:

https://github.com/data-skeptic/dataskeptic.com/blob/master/public/css/style.css
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Cart.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/CartQuantity.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/CountrySelector.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Sidebar.js

**Comment by glozhkovoy** [comment]
> Note that the mobile design has a fixed header and fixed footer. When the cart has more items than can fit on the screen, the last partially visible one fades out and the middle section can be scrolled.

<img width="355" alt="screen shot 2017-02-17 at 11 20 07 pm" src="https://cloud.githubusercontent.com/assets/20016615/23083697/a75943b2-f567-11e6-9faa-75d32792fff8.png">

Also this commit contains new cart icon.

Check it now - https://github.com/data-skeptic/dataskeptic.com/pull/48

**Comment by glozhkovoy** [comment]
https://github.com/data-skeptic/dataskeptic.com/pull/48
