### ISSUE TITLE
Very small UI glitch

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#275]
It's hard to notice, but the "g" in reading is cropped off.  Can we fix it?

![screen shot 2017-12-22 at 8 14 43 am](https://user-images.githubusercontent.com/1054674/34304816-3172433a-e6f0-11e7-8bf0-ff335475cae5.png)

**Comment by kylepolich** [comment]
I noticed this also occurs in some of the h2 titles.  Please adjust CSS.

**Comment by glozhkovoy** [comment]
@kylepolich Could you specify the places? This is context relative issue and have no general solution

**Comment by kylepolich** [comment]
@glozhkovoy I only noticed it in this one place.  For certain, let's fix it there.  I think I saw it in the BlogItem headline as well, possibly.  Can we add a little more `margin-bottom` (or whatever is appropriate) whenever the title is there.
