### ISSUE TITLE
Blog cache better but still not working

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#276]
See this recording:

http://recordit.co/096HdoYDZc

Steps shown in recording:

- Latest code from `dev` is running locally.  There is a recent post which is loaded, cached, and rendered correctly.  Everything is good
- I refresh to confirm
- Next, I use my deployment script to make a small update to the content
- Next, I refresh (WITHOUT /api/refresh) to confirm that change is not reflected yet.  Everything is good
- Then, I call /api/refresh, then I refresh the page.  Now the page is MISSING!

I ended the recording there.  If you wait ~30 seconds, then hit refresh, now the updated blog post is VISIBLE!

Very strange!  Why does it go to 404 and require time?  We need to have no interruption.

You might be wondering if the problem is in my deploy.py file.  What if it makes some mistake?  I don't think this is a possible explanation.  You can see that the script exits in the video.  It pushes a file to S3 and updated Dynamo, then exits.  Therefore, no further changes in the backend can happen.  If you wait and refresh the localhost, the updated content will appear.  Therefore, II think the issue must be in this repository.

**Comment by glozhkovoy** [comment]
Oh, yeah. 

Is my fault: I decided to hard refresh the cache (in other words make it empty once you start the refresh). 

It explains why you saw 404 — actually blog cache was empty for the moment when it will be refetched. 

I’ll prepere simple solution soon.
