### ISSUE TITLE
Implement new /footer

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#28]
The current footer can be seen on any page at: https://dataskeptic.com/

Right now, it begins with five rectangle links (itunes, google play, stitcher, license, rss).  These will be removed.

Below that are ads.  The ads will STAY, and then below that, a new footer will appear as shown in this screenshot:

https://s3.amazonaws.com/dataskeptic-static/mobile/index.html#artboard3

The above design is for desktop only.  For mobile, the footer should become invisible.

You should implement these changes by editing ONLY these files:

https://github.com/data-skeptic/dataskeptic.com/blob/master/public/css/style.css
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Footer.js

**Comment by glozhkovoy** [comment]
Delivered #41.

Includes little design changes on mobile/tablet.

**Comment by kylepolich** [comment]
Great work.
