### ISSUE TITLE
How do we secure the Claudia.js api?

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#286]
Right now we have one API that has the environment embedded in the url:

https://xxx.execute-api.us-east-1.amazonaws.com/dev/version

dev or prod can be used.

1) People can learn this URL by inspecting our code.  How can we make sure this API cannot be called directly by outside people?

2) Right now, a developer has access to dev and prod.  They should use `dev` for development purposes.  It would be best if they got 500 error when trying `prod`.  How can we make a developer get access denied on prod but full access to dev?

**Comment by glozhkovoy** [comment]
1. Retrieve API_URL from the config file.
2. Have an unique KEY at the config file.

Server could work as a proxy, so user will never know `real` lambda route.

**Comment by kylepolich** [comment]
Good plan.  Currently, the site has a mix of functionality.  Some routes to /api and some contacts the aws lambda endpoint directly.

Please add proxy in `serverInit.js` for the `load_blogs` function.  Currently it calls API directly.  Please create a proxy.

Add this element to the config/config.json file to get the base_url:

{"prod": {"base_api": <lambda>}}

Remove line 18 (`var base_url = "https://4sev...."` and move that value to the config.

Do the same activities in these files:
`CmsReducer.js`
`MemberPortalReducer.js`

Do not introduce new files.
