### ISSUE TITLE
Implement new player

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#29]
To see the current player:
* visit https://dataskeptic.com/
* Click the play button in the "Latest Episode" box
* The player will appear below the header

The functionality will remain, but the design needs to be updated to these designs:

Desktop:
https://s3.amazonaws.com/dataskeptic-static/mobile/index.html#artboard4

Mobile:
https://s3.amazonaws.com/dataskeptic-static/mobile/index.html#artboard5

You should implement these changes by editing ONLY these files:

https://github.com/data-skeptic/dataskeptic.com/blob/master/public/css/style.css
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Player.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/PlayerProgressBar.js

**Comment by glozhkovoy** [comment]
Delivered PR for this issue. Check it https://github.com/data-skeptic/dataskeptic.com/pull/37

**Comment by kylepolich** [comment]
These updates are fantastic.  Thank you for adding the shadow, it helps a lot.
