### ISSUE TITLE
Update the /checkout page

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#30]
Currently, you can view our checkout page here: https://dataskeptic.com/checkout

Update this page to match the following desktop design:

https://s3.amazonaws.com/dataskeptic-static/mobile/index.html#artboard8

The sidebar "Order Summary" is going to be redesigned in this ticket:
https://github.com/data-skeptic/dataskeptic.com/issues/27

You should NOT do this ticket until those updates are available.

There is no mobile example of the design.  Please propose a streamlined mobile version.

You should implement these changes by editing ONLY these files:

https://github.com/data-skeptic/dataskeptic.com/blob/master/public/css/style.css
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Checkout.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/AddressForm.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Cart.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/CreditCardForm.js
https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/SizeSelector.js

**Comment by kylepolich** [comment]
The existing page has some error handling that is not done in a very nice way.  The design does not give any guidance on how to report errors.  Can you please make your best guess about how to provide feedback to the user?  If there are questions, we can discuss on Slack.

**Comment by glozhkovoy** [comment]
Design delivered in https://github.com/data-skeptic/dataskeptic.com/pull/53

**Comment by glozhkovoy** [comment]
Errors will be implemented in https://github.com/data-skeptic/dataskeptic.com/issues/52
