### ISSUE TITLE
Related content attach mp3 to our player

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#305]
When blog loads, check for related content of `type` = `mp3` via the lambda API with this call:

/dev/blog/relatedcontent/get?blog_id=266

It returns this:

```
[
{
content_id: 21,
blog_id: 266,
dest: "https://s3.amazonaws.com/data-skeptic-bonus-feed/episodes/2017/rohan-kumar.mp3",
type: "mp3",
title: "Rohan Kumar full interview",
body: "",
created_date: "2018-01-02T02:31:45.000Z"
}
]
```

If type type is "mp3" (as above), then use the EpisodePlayer.js file to put a player on the page and allow it to link into our typical Howler player.

Reference link: https://dataskeptic.com/blog/tools-and-techniques/2017/interview-with-rohan-kumar-gm-for-the-database-systems-group-at-microsoft

Note:  I will remove the embedded player from the post once this ticket is complete.

**Comment by kylepolich** [comment]
Related to #303 and #304

**Comment by kylepolich** [comment]
@glozhkovoy , I don't understand why this is marked as Blocked.  To try and understand, I started working on the other two tickets related to this.  They were trivial to implement.  I am moving this back to Ready.  If it is blocked, please clarify why.

**Comment by glozhkovoy** [comment]
As I could remember, API doesn't returned this blog data. That's why I was blocked

**Comment by glozhkovoy** [comment]
@kylepolich Ok. Got it. Now we don't need to call a lambda. Related content is a part of blog. Good decision
