### ISSUE TITLE
Create an RSS feed of blog content

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#31]
Create a new feature on the web site that returns an XML file of the blog's content in the same schema used here:

http://science.sciencemag.org/rss/twis.xml?_ga=1.162948156.188283010.1486871507

An existing endpoint exists here, but in the wrong format:

https://dataskeptic.com/api/blog

You can find the code behind that response here:

https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/backend/get_blogs.js

Create a new file called get_rss_feed.js which returns XML instead of JSON.

**Comment by glozhkovoy** [comment]
Here we are https://github.com/data-skeptic/dataskeptic.com/pull/54

**Comment by kylepolich** [comment]
Looks great, thanks!
