### ISSUE TITLE
Add pagination to blog

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#32]
Blog pages should only retrieve the first 10 items.  If 10 or fewer entries exist for the category, show no navigation.  If 10 or more exist, show a typical navigation like this:

previous      1   2   3   4   5   6  ... 99    next

Your changes should be confined to the files listed below, although you may introduce new files for the new navigation element.  The nav should appear at the top and bottom of the list of entries.

style.css (add styles for the new navigation element.

https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/components/Blog.js
This file contains the logic for showing the blog and also makes a call to the `get_blogs_list` function.  You will likely need to edit the parameters required by this function.  It can be found in:

https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/utils/redux_loader.js
This file will use `my_cache` when it's server side, or use the site's existing API if client side.  The API supports pagination already.  It accepts `limit` and `offset`.  

Example:
https://dataskeptic.com/api/blog?limit=2&offset=3

However, the API does not specify the total number of items, which will be required to determine the number of pages.  You will need to enhance the API to add this feature.  The function with handles the API call shown above is:

https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/backend/get_blogs.js

**Comment by glozhkovoy** [comment]
Almost done.

Need help with this lines.

```var focus_episode = oepisodes.focus_episode
        if (focus_episode.episode != undefined) {
        	debugger;
        	console.log("!!!")
        	console.log(blog_focus)
        	console.log(focus_episode)
        	if (focus_episode.episode.guid == blog_focus.blog.guid) {
        		try {
        			top = (
        				<div className="home-player">
        					<LatestEpisodePlayer guid={focus_episode.guid} />
        				</div>
        			)
        			isEpisode = true
        		}
        		catch (err) {
        			console.log(err)
        			top = <div></div>
        		}
        	}
        }
        var bot = <div></div>
        if (isEpisode && false) {
        	var tm = oblogs.transcript_map
        	if (tm != undefined) {
        		var guid = blog_focus.blog.guid
        		var b = tm[guid]
        		if (b != undefined) {
        			if (b.prettyname != undefined) {
        				if (b.prettyname.indexOf('/transcripts/') == -1) {
        					var pn = "/blog" + b.prettyname
        					bot = (
        						<div className='blog-transcript-link'>
        							Read the full transcript here:
        							<Link to={pn}>{title} transcripts</Link>.
        						</div>
        					)
        				}
        			}
        		}
        	}```

**Comment by kylepolich** [comment]
@glozhkovoy , there are two features in the code above ^.

`focus_episode.episode` is like `blog_focus.blog`.  If this is set, then an episode is "loaded".  If that episode's `guid` matches the `guid` for the blog, then we want to show the  `<LatestEpisodePlayer />` on the page.

The second part is for showing the transcripts, but we are going to change the way that works.  Obviously `if (isEpisode && false)` will never execute.  We turned it off when a bug was found.  That code can be deleted.

**Comment by kylepolich** [comment]
@glozhkovoy make sure to merge the changes I pushed to `dev`.  I addressed some of these issues.

**Comment by kylepolich** [comment]
There seems to be a bug:

http://recordit.co/fPvOKNK39Y

Repeat:

1. Go to https://dataskeptic.com/blog/
2. Scroll to bottom
3. Click "23" (right now it's the last number available)
4. "Loading..." forever

**Comment by glozhkovoy** [comment]
Reproduced and fixed.

**Comment by kylepolich** [comment]
Confirmed.  Thanks!
