### ISSUE TITLE
Use localStorage to persist cart

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#33]
Introduce `localStorage` so client side can capture details about the user session.  It should NOT capture the entire redux state.  It should only capture explicit elements described in this and future tickets which may add more things to store.

Make sure that on refresh, a check is introduced with looks for this data in localStorage.  The stored variable should also contain a `version`, and if the `localStorage` every stores something different than the server side's most current version, the values should be cleared.

**Comment by glozhkovoy** [comment]
This is not almost ready after PR. I'm going to add serverside validation

**Comment by kylepolich** [comment]
I merged these changes in because they look good.  I will leave this open while serverside validation is being developed.  I think it can be lower priority than other Issues.

**Comment by kylepolich** [comment]
Do we still need serverside validation?

**Comment by glozhkovoy** [comment]
It resolved by version constant in SiteReducer.
