### ISSUE TITLE
Setup login with LocalStrategy backend

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#356]
Right now we have GoogleStrategy for passport.  The site supports LinkedinStrategy, but we are not yet using it.  I want to also add "Create Account" where they make an account in our database.

DO  NOT DO ANY CODE

For now, I just want to have a list of the steps required to implement this.  Please give the technical plan for review.

**Comment by glozhkovoy** [comment]
I'm confused. 

`LocalStrategy` means login with login/password chain.

You're asking about the `Create Account` feature?

**Comment by kylepolich** [comment]
KYLE to provide these two endpoints:
1) Get user data by email
2) Create user by email and password

{"email": "kyle@ds.com", "password": "blah"}

**Comment by kylepolich** [comment]
@glozhkovoy I can add these two functions to the API, but it seems incomplete.  How will you verify the password in the future?

**Comment by kylepolich** [comment]
@glozhkovoy , I added two new API endpoints, but I still need more clarification from you.

New endpoints:
GET: `/user/get?email=kyle@dataskeptic.com`
POST: `/user/add`   `{"email": "kyle@dataskeptic.com", "password": "blah"}`

Seems like something is missing.  How will you verify login in the future?

Also, the password needs to be carefully encrypted and salted.  I think this should take place on the server and the database should only have the encrypted version.  Can you always send the encrypted version of the password (both for `/user/add` and whatever verification we add)?

**Comment by glozhkovoy** [comment]
>GET: /user/get?email=kyle@dataskeptic.com

Could it also return the `password` attribute ? 

> I think this should take place on the server and the database should only have the encrypted version.

Sure thing. Password on the server is always salted and encrypted. Check here https://github.com/data-skeptic/dataskeptic.com/compare/local_login?expand=1#diff-72c5f6d1dfc53ce69309c20764fcb15eR86 and here https://github.com/data-skeptic/dataskeptic.com/compare/local_login?expand=1#diff-72c5f6d1dfc53ce69309c20764fcb15eR138

**Comment by kylepolich** [comment]
Ok, I have updated the API to return password also.

**Comment by glozhkovoy** [comment]
@kylepolich I checked the PR https://github.com/data-skeptic/dataskeptic.com/pull/406. Now it works correctly and ready for testing
