### ISSUE TITLE
Request for Proposal Page

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#39]
Create a new page:

http://dataskeptic.com/rfc

This is the "Request for Comment" page where people can submit responses to topics.

The page layout should be something like this:

```
<Header />
  <div className="rfc">
    <h2>Request for Comment</h2>
    <p>Thanks for considering contributing your thoughts for an upcoming episode.  Please review the topic below and share any thoughts you have on it.  We aren't always able to use every comment submitted, but we will do our best and appreciate your input.</p>
    <p><b>Current topic:</b> {topic}</p>
    <p>{long_description}</p>
    <b>Time to comment:</b>
    <CountdownClock deadline={deadline} />
    <p>Name: <input id="name" /></p>
    <p>Email: <input id="email" /></p>
    <CommentFormatContainer />
  </div>
</Footer />
```
The CommentFormatContainer should be three large buttons with icons (I will add a sample image in the comments).  When the user clicks on one of these 3 buttons, a new input field will appear below.

Option 1 - textarea - just a text box

Option 2 - upload - drag and drop or use <input type="file" />

Option 3 - microphone - record via computer/phone's microphone (take care of getting permissions)

Anything uploaded (text, file, audio clip) should be pushed to S3 and emailed to kyle@dataskeptic.com with a link to the S3 URL.

**Comment by kylepolich** [comment]
![img_20170215_113027](https://cloud.githubusercontent.com/assets/1054674/22992096/7b4989bc-f373-11e6-83ba-9f662ca61018.jpg)

For the 3 buttons that select the upload type, use these three images as placeholders.  The designer will eventually replace these:

![text response](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Keyboard-icon_Wikipedians.svg/800px-Keyboard-icon_Wikipedians.svg.png)

![upload file or audio clip](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Outputs_icon.svg/2000px-Outputs_icon.svg.png)

![record comment](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Ic_mic_48px.svg/2000px-Ic_mic_48px.svg.png)

**Comment by kylepolich** [comment]
Use this API endpoint to lookup the metadata: http://localhost:3000/api/rfc/list

I just added a stub on `dev` branch

**Comment by kylepolich** [comment]
If {deadline} is in the past, disable the upload choice and show this message:

This RFC has closed.  Please check back later, as we open new topics regularly.

**Comment by kylepolich** [comment]
This depends on #42

**Comment by kylepolich** [comment]
I created a DynamoDB table that has this entry:

```{
  "deadline": "2017-04-15",
  "id": "test-request",
  "long_description": "What does it mean to test?  From the machine's point of view, a good test is one that has a long paragraph here which is closer to what the actual length will be.  In generally, I expect to write perhaps 300 words.  That's not that many!  The layout should adapt nicely with a longer length.  We'll try not to get it too long.",
  "topic": "Our topic this month is test",
  "active": true
}```

The table name is `rfc`

**Comment by glozhkovoy** [comment]
Done. https://github.com/data-skeptic/dataskeptic.com/pull/100/commits/72e358409054faf9102e0347f155a6c0fbb64693
