### ISSUE TITLE
Fix distorted image

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#391]
The original specification looks like this:

![screen shot 2018-01-22 at 7 50 22 am](https://user-images.githubusercontent.com/1054674/35229787-24382330-ff49-11e7-870c-322cd60765fc.png)

But the delivered code has a distorted image:

![screen shot 2018-01-22 at 7 50 52 am](https://user-images.githubusercontent.com/1054674/35229802-2e718ecc-ff49-11e7-88f9-7de3c10dfab7.png)

Fix the image.

**Comment by urchindev** [comment]
got it

**Comment by kylepolich** [comment]
@urchindev You are looking in the wrong place.  Please review the two images I put into this page above.    You will see in the designer's image that the lines have a gradient of color.  The screenshot of the site using your delivered code shows very distorted colors that are not a gradient.
