### ISSUE TITLE
Guest images

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#398]
Take this page for example:

https://dataskeptic.com/blog/episodes/2018/neuroscience-frontiers

There are four Guests which are populated dynamically through the `related-content` system of type `people`.

Using the same API, retrieve the images for all such people.  Put the faces on this page:

https://dataskeptic.com/podcast

The faces associated with the episode (not all episodes have this, some have 1, some have more).  Make them small circles (just like on the About Us page) and place them according to the mobile and desktop images shown below.

**Comment by kylepolich** [comment]
![ss1](https://user-images.githubusercontent.com/1054674/35265154-2abc8c7e-ffd4-11e7-9fcf-9cf612c73ca2.png)
![ss2](https://user-images.githubusercontent.com/1054674/35265155-2acf741a-ffd4-11e7-9f11-4b72bba8de4b.png)

**Comment by glozhkovoy** [comment]
Hm. Could you remember how to fetch related content for episode in this case? There is no `blog_id` for items. Moreover, maybe the greatest solution is to provide url from lambda (how it works on blogs now)

**Comment by kylepolich** [comment]
Yes, this is a little tricky.  Unfortunately, it has to be this way because of how Libsyn works.  But you can do it in the following method:

`/blog/list?guid=642bd344413becadc177b428285b7d26`
