### ISSUE TITLE
Replace ? with animation

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#399]
Visit or refresh the homepage.  Click the play button on the LatestEpisode Component.  The button's icon will become a ? while it is loading.  After the file is loaded, ? turns into two bars (pause).

The question mark should be replaced with something giving a more clear user experience.  Use the image from this ticket.

http://g.recordit.co/UJ741zPX8u.gif

**Comment by kylepolich** [comment]
![load](https://user-images.githubusercontent.com/1054674/35266150-2bb3e476-ffd7-11e7-9adc-761991758920.gif)

**Comment by glozhkovoy** [comment]
It looks ugly on background 

![k3poijzwtm](https://user-images.githubusercontent.com/20016615/35274554-24b2a36a-0045-11e8-8022-be7289ff9514.gif)
