### ISSUE TITLE
Add author images on homepage

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#403]
We have 3 podcasts on the home page.  The `featured_blog` already show's the author's image.  Put the image to the left of the title and description.  The text should shift to the right.

Please add the author image to `feature_2` and `feature_3` which are at the bottom.

Similarly, put the Guest images in the `EpisodePlayer.js` just like recent work done on the `Podcast.js` page.  Put the images (when available) below the "View More" link, inside the grey box.

**Comment by glozhkovoy** [comment]
> Put the image to the left of the title and description. The text should shift to the right.
In other words make something like on blog page?

<img width="545" alt="screen shot 2018-01-25 at 6 48 00 pm" src="https://user-images.githubusercontent.com/20016615/35400742-49ce24be-0200-11e8-87ce-5e9ba0958a25.png">

P.S. almost done 
![screencapture-localhost-3000-1516898918039](https://user-images.githubusercontent.com/20016615/35400781-61364ed8-0200-11e8-8dc4-d9eb6712dbf5.png)
