### ISSUE TITLE
URGENT FIX NEEDED

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#420]
Recent updates have broken production again.  

REPRODUCIBILITY:
If you visit the home page, the wrong "Latest Episode" is shown.
If you click on Podcasts, it shows the old episode, then snaps into an updated version with the correct items.

**If you cannot fix this quickly, send a PR which rolls back the recent changes.**

We need more testing going forward.
This CANNOT happen again.

http://g.recordit.co/Z0ssLJfnL2.gif

**Comment by glozhkovoy** [comment]
Actually it works correctly... check the `/prod/cms/homepage` api response. 
`latest_episode` is invalid

**Comment by kylepolich** [comment]
@glozhkovoy I will check that.  It could explain the homepage.  The more important problem is the jump cut shown in the animation.

**Comment by glozhkovoy** [comment]
Regarding the jump. 

CMSReducer pre populate the episode list with the latest episode https://github.com/data-skeptic/dataskeptic.com/blob/master/shared/reducers/CmsReducer.js#L203
