### ISSUE TITLE
"Propose Edit" button for blog

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#43]
At the end of all blog posts, we should add a button that says "Propose Edit" which takes the user to the corresponding source code page on github in edit mode.  For example:

https://github.com/data-skeptic/blog/edit/master/opinions/2017/appeal-to-authority.md

If the page comes from a Jupyter notebook, show this page instead of the edit page (edit page is json source, which is not useful):

https://github.com/data-skeptic/blog/blob/master/data-collection/regulations.gov.ipynb

**Comment by glozhkovoy** [comment]
Already delivered.
