### ISSUE TITLE
Add image to BlogListItem

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#431]
If the blog has a related content with type: "homepage-image", then put this image to the left of the title/author/abstract.

This needs to happen on /blog and /contributor/*

Move the author image on /blog to look more like the homepage to give room for the image from the post.

Also, place the image on the BlogItem similar to this page where an image was embedded manually:

https://dataskeptic.com/blog/episodes/2018/the-agent-model-of-intelligence

For the "homepage-image" image, place it floating BELOW the title, and make it push the first paragraph to the right.

Make the format work well on mobile too.

**Comment by glozhkovoy** [comment]
It's looks cool when post have a preview.

<img width="991" alt="screen shot 2018-01-30 at 1 46 56 pm" src="https://user-images.githubusercontent.com/20016615/35564786-10be3fa2-05c4-11e8-9b8e-fb81757eaa9e.png">

But awful when it hasn't

<img width="1046" alt="screen shot 2018-01-30 at 1 47 00 pm" src="https://user-images.githubusercontent.com/20016615/35564811-2414e088-05c4-11e8-90ef-66fcf91d497e.png">

Maybe put preview to the right side?

**Comment by kylepolich** [comment]
@glozhkovoy I agree it looks awful without.  Per the other Issue I opened, let's not indent the image-less ones.  I am going to be having a photo on almost everything going forward so it should be ok, but for older posts, move to the right.
