### ISSUE TITLE
Bug in date display

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#45]
![date-bug](https://cloud.githubusercontent.com/assets/1054674/23034922/4848388c-f432-11e6-9aa3-d514810dcdf9.gif)

In the above image, you can see that the server side renders it one way, and then the client re-renders it and changes the date.  This is probably due to different time zones.

There are two solutions:

1) Make the server aware of client's time zone and always do rendering in appropriate time zone

2) Fix server and client side to both always return Pacific Standard Time

Please implement whichever solution is easiest to implement.

**Comment by glozhkovoy** [comment]
Seems like fixed in https://github.com/data-skeptic/dataskeptic.com/tree/blog-pagination branch.
