### ISSUE TITLE
Contributors page shows in wrong order

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#450]
Production issue

Christine Zhang is listed as the top Contributor but this is not the correct order.  Order is given by the API.  API here:

https://4sevcujref.execute-api.us-east-1.amazonaws.com/prod/blog/contributors/list

shows Kyle is the top Contributor. 

Fix the ordering.

**Comment by glozhkovoy** [comment]
Didn't realized we have `sort_rank` in response

**Comment by kylepolich** [comment]
@gleblozhkovoy Why is this marked "In Review".  It is still not fixed.  Please fix.

**Comment by gleblozhkovoy** [comment]
That's mistype issue. I sorted contributors by `sort_order` not a `sort_rank`. Check https://github.com/data-skeptic/dataskeptic.com/pull/456
