### ISSUE TITLE
Layout changes

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#455]
If one Guest is present, center it.
<img width="271" alt="screen shot 2018-02-02 at 10 21 23 am" src="https://user-images.githubusercontent.com/1054674/35748467-fd8ebf6a-0802-11e8-91e5-10c568bb78ec.png">

If two guests, centered in a row.

If three guests, centered in a row.

If four guests, centered in TWO rows (2x2)
<img width="248" alt="screen shot 2018-02-02 at 10 21 29 am" src="https://user-images.githubusercontent.com/1054674/35748468-fda36f50-0802-11e8-88ee-c1c5c305f0d6.png">

**Comment by gleblozhkovoy** [comment]
<img width="298" alt="screen shot 2018-02-09 at 8 26 36 am" src="https://user-images.githubusercontent.com/20016615/36014758-06aa5d0e-0d74-11e8-8a14-572a5c1dbc01.png">

**Comment by gleblozhkovoy** [comment]
<img width="741" alt="screen shot 2018-02-09 at 8 27 19 am" src="https://user-images.githubusercontent.com/20016615/36014762-0d6a3312-0d74-11e8-98e8-abf6cd66ddce.png">

https://atlassian.design/guidelines/product/components/avatars

Check the `Avatar Groups` section

**Comment by kylepolich** [comment]
@gleblozhkovoy great example, let's follow that style.
