### ISSUE TITLE
Reduce the use of ipinfo.io

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#460]
In server.jsx you will see that we use `ipinfo.io` to get data on users.  Right now, this is called on every server call, which is too much.  Please store this information somehow (user cookie?).  If the data can be retrieved without calling ipinfo.io, then use the stored version.

**Comment by m-cameron** [comment]
Remote API is slow due to network latency. It easily add up additional 100ms per call and does not scale up very well.

Is it possible to use a local geolocation database such as [IP2Location LITE](https://www.ip2location.com)?
