### ISSUE TITLE
Missing icons from Contact Us now available

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#486]
https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/arrow_down.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/arrow_up.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/facebook-square-FontAwesome.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/mail_outline.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/record.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/slack.jpg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/twitter-square-FontAwesome.svg

**Comment by gleblozhkovoy** [comment]
Links are broken

**Comment by kylepolich** [comment]
@gleblozhkovoy fixed now

**Comment by gleblozhkovoy** [comment]
Unfortunately the sources seems to be broken from the beginning 

<img width="1020" alt="screen shot 2018-02-21 at 5 29 01 pm" src="https://user-images.githubusercontent.com/20016615/36488681-beb7b092-172c-11e8-9fbd-f1c472fa9dec.png">

**Comment by kylepolich** [comment]
https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/twitter-square+-+FontAwesome.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/microphone+-+FontAwesome.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/mail_outline+-+material+copy.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/logo-slack.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/keyboard_arrow_down+-+material.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/facebook-square+-+FontAwesome.svg

https://s3.amazonaws.com/dataskeptic.com/img/2018/contact-us/Rectangle+Copy+13.svg
