### ISSUE TITLE
Update config / boot of site

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#490]
Right now, the site assumes that the config file is available locally as config/config.json.  We want to move more towards environment variables for configuration.  However, our configuration is fairly complication.  I want to keep it as a file, rather than pull out every small detail to an ENV var.

Thus, the site will be provided with three environment variables:

AWS_ACCESS_KEY
AWS_SECRET_KEY
AWS_CONFIG_S3_BUCKET
AWS_CONFIG_S3_KEY

The new site code should behave as follows:
1) Check if config/config.json exists.  If so, you are done!
2) If not, retrieve it from S3
3) Store the downloaded version in config/config.json for next time
4) Use the downloaded version to finish initialization

During the booting process of the site, there will be some delay as the config file is downloaded.  This is not a problem.  However, once it is available, the site should then proceed with the rest of the Promises to finish the load.

@gleblozhkovoy, I will have you work with @jing9932 on some of the details.

**Comment by jing9932** [comment]
Got it.

**Comment by kylepolich** [comment]
Today, the site's config file is nested by environment.  For example, this is allowed:

```
{
  "dev": { ... },
  "prod": { ... }
}
```

This was a poor choice on my part.  Now that we are adjusting the config, let's remove that extra layer.

I have put the `dev` and `prod` versions into S3 by splitting my config file into two.  When I share the S3 bucket/key, you can expect that the ENV key described above will be removed.
