### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#50]
There seems to be a problem where the site requires more and more memory with time until it runs out.  I believe the problem may be in `server.jsx` in the `doRefresh` function.  This has the purpose of getting any updates to blogs, episoes, and products, and loading them into `global`.  I am guessing the old records are not being removed and garbage collected.

**Comment by kylepolich** [comment]
It sounds like this might be caused by `getContributors`

**Comment by kylepolich** [comment]
I think this is fixed now.  Great find.

**Comment by glozhkovoy** [comment]
But I still think we should move to the Redis #98
