### ISSUE TITLE
Updates to dev break all playback

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#504]
Player no longer works.

<img width="1227" alt="screen shot 2018-02-25 at 10 04 34 pm" src="https://user-images.githubusercontent.com/1054674/36655521-067cc5a4-1a78-11e8-8a0b-7291b78e592e.png">

**Comment by gleblozhkovoy** [comment]
That bug was fixed at https://github.com/data-skeptic/dataskeptic.com/pull/495.

Case: load site on any page, after that go the home

**Comment by kylepolich** [comment]
@gleblozhkovoy That branch is already merged to dev and this problem exists on the latest of dev

**Comment by gleblozhkovoy** [comment]
Here the reason why it fails before:
https://github.com/data-skeptic/dataskeptic.com/commit/179fe51a64ab4725e109668db81b04b8058de04b#diff-e972ac30afb36552ede201de6600dac8L37

We has two endpoints (yes, it's strange). One of them consist preview, mp3 link and general information. Second one has `relative` data to show guests

**Comment by gleblozhkovoy** [comment]
Right now if you don't preload episode from the server (load home with ssr) it fetch data only from lambda which have no mp3
