### ISSUE TITLE
The picture says it all

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#527]
<img width="393" alt="screen shot 2018-03-02 at 6 17 10 pm" src="https://user-images.githubusercontent.com/1054674/36929489-075da6f6-1e46-11e8-8503-89c97233b65c.png">

**Comment by gleblozhkovoy** [comment]
I like this idea so much. Will deliver ASAP

**Comment by gleblozhkovoy** [comment]
Please check the latest

<img width="399" alt="screen shot 2018-03-03 at 5 49 12 pm" src="https://user-images.githubusercontent.com/20016615/36936237-3589d750-1f0b-11e8-8ca7-24e718460fac.png">
