### ISSUE TITLE
Inactivity message

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#529]
I want to do something like this:

```
	setTimeout(function() {
		reply({text: "Still there?  Let me know what you think of the bot by DMing me on Slack!  I would appreciate your candid feedback"}, 'kyle')
		// still there?
	}, 1000 * 30)
```

However, I want the counter to reset after every user message.  It should only appear after 30 sections of no typing or messages from the user.

**Comment by gleblozhkovoy** [comment]
![xk1fjnaqza](https://user-images.githubusercontent.com/20016615/36984957-b414fa7a-209e-11e8-900b-dbcbc7553f54.gif)

Check simple configuration here https://github.com/data-skeptic/dataskeptic.com/commit/2457a46dc81bb9d1abd9b94332b7442d8514d2f7#diff-7ea3772f3e8cde47ecc31c267db6b71bR186
