### ISSUE TITLE
Thinking state in UI

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#532]
I made a property called `thinking` in the state of ChatbotReducer.  It is `true` iff the Bot is waiting on some slow async.

Please make some UI indicator that the BOT is going to give a response soon.  Similiar to the idea of saying "Kyle is typing..."

**Comment by gleblozhkovoy** [comment]
I simulated very long request to show animation/logic

![rjjylxazer](https://user-images.githubusercontent.com/20016615/36983468-218ac534-209b-11e8-9a0c-58e558aa8593.gif)
