### ISSUE TITLE
Contributors on Blog Page

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#534]
Currently, each blog has a single `author`.  It is a string which can be looked up in the `contributors` dictionary.

We are going to move away from this format.  However, the move will be backwards compatible.

The new functionality will allow for multiple contributors to be associated with each blog post.  The existing API has already been updated in DEV to support this.  See example:

https://xxx.execute-api.us-east-1.amazonaws.com/dev/blog/list?blog_id=326

There you will find `contributors` list.  It will be empty for most Blogs.  If this is present, then the Blog page should NOT use the `author` from the `blog`.  Ignore it, and instead use `contributors` to give a list.

Notice that the new objects have more information.  Now, the Contributor has a `contribution` field which describes what they did.  For example, "writer" and "editor" could be labels.  This label needs to be incorporated into the bio.

**Comment by gleblozhkovoy** [comment]
Could you anyway put real data to some blog post item?

**Comment by kylepolich** [comment]
For blog_id=326, real data is provided.

**Comment by gleblozhkovoy** [comment]
Oh, yes. I have looked at `blog/list?` endpoint response

**Comment by kylepolich** [comment]
Yes, it will be returned via that endpoint.  For right now, only one post.  But that post has real data.
