### ISSUE TITLE
Blog Content Rendering

### ISSUE THREAD

**Issue by gliblozhkovyi** [data-skeptic/dataskeptic.com#543]
I found extremely interesting thing. Guys from github also use markdown files for articles – example https://opensource.guide/legal/#are-public-github-projects-open-source source code here https://raw.githubusercontent.com/github/opensource.guide/master/_articles/legal.md. 

They use complex typography styles for inner content (for h1, h2.., lists). That allows to render any template nice to look.

For example they use `aside` html tag to create boxes like this one 
<img width="877" alt="screen shot 2018-03-05 at 7 45 00 pm" src="https://user-images.githubusercontent.com/20016615/36990560-c4cdd468-20ad-11e8-8140-487239b1345e.png">

Or even like this
<img width="838" alt="screen shot 2018-03-05 at 7 45 10 pm" src="https://user-images.githubusercontent.com/20016615/36990546-bce7358c-20ad-11e8-89c2-2d0fb2506892.png">

We could follow that practice and describe some tags for `tables`, `image gallery`, `links set`. Style code blocks. Or even `columns` layout.

**Comment by kylepolich** [comment]
I like this a lot.  Let's discuss it next time we talk.
