### ISSUE TITLE
One more drop and upload.  This on in admin

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#546]
These uploads need to go to a very specific place in S3.

The are in the `dataskeptic.com` bucket or `dev.dataskeptic.com` (add it to the config).  The s3Key is like this:

/blog/meta/2018/ad-free-podcast-feed/images

prettyname + "/images"

![admin-upload](https://user-images.githubusercontent.com/1054674/37014965-f70d5fb0-20b8-11e8-8cdc-2f02adb08387.png)

Validate that the image is 400x400.  No other dimensions allowed.

When the user uploads the image correctly, Add it as "related content" which is done manually today here:

<img width="479" alt="screen shot 2018-03-05 at 9 09 14 pm" src="https://user-images.githubusercontent.com/1054674/37015068-8480fa1e-20b9-11e8-890e-45779f746aab.png">

The 400x400 image is our `homepage-image` for the type, alt text should be the blog's title, and image url is the destination in s3.

If the user uploads a second image, it is ok to overwrite the old one in S3, or let it be an orphan file.  But make sure to only allow ONE Related Content of type `homepage-image`.

**Comment by kylepolich** [comment]
The design I did in the first image is optional.  You can change it if you have a better idea.

**Comment by kylepolich** [comment]
Also, I wrote #550 which is related.  This ticket is a little confusing.  Please review #550.  For the case of SELECT equallying homepage-image, in that case, allow drag and drop upload.  In the other cases.

**Comment by kylepolich** [comment]
In fact, given #550, my drawing makes no sense.  I think if you review the existing Components, it will be clear how to merge these ideas.  Please use your best judgement for making the UI.

**Comment by gleblozhkovoy** [comment]
Sneak peek of `Preview Upload Field` component

![usjw7tpeoi](https://user-images.githubusercontent.com/20016615/37155290-318d3730-22eb-11e8-80cc-32e909dfdebd.gif)
