### ISSUE TITLE
ContactForm waiting icon

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#55]
Right now when you use the ContactForm, after you hit "Send", there is a wait for the confirmation that the email was sent.  However, there is no indication that the user should wait.  We should use Loading_icon.gif while we wait for confirmation.

**Comment by glozhkovoy** [comment]
Done with cool validation and loader https://github.com/data-skeptic/dataskeptic.com/pull/57

**Comment by kylepolich** [comment]
Looks fantastic.
