### ISSUE TITLE
Inactivity message not working

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#558]
I see it immediately every request on `rcw`

http://g.recordit.co/LvLrVWhq5Y.gif

**Comment by gleblozhkovoy** [comment]
It was implemented just for test purpose. Now it configured to one second (to check it works). 

Please, change it as you need
https://github.com/data-skeptic/dataskeptic.com/blob/rcw/shared/Contacts/Routes/ContactUs.js#L188
