### ISSUE TITLE
What is the source of the duplication? (production issue)

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#559]
<img width="290" alt="screen shot 2018-03-07 at 4 04 12 pm" src="https://user-images.githubusercontent.com/1054674/37125403-4c73379a-2221-11e8-8f1b-455adb226410.png">

Please trace down the issue.  If it's the backend / API, then it's my fault.

**Comment by gleblozhkovoy** [comment]
Lambda's response for this item is broken by some reason

<img width="355" alt="screen shot 2018-03-08 at 2 11 41 am" src="https://user-images.githubusercontent.com/20016615/37125593-118b6418-2276-11e8-8bf8-ff466f52ae46.png">
