### ISSUE TITLE
Inactive message bugs

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#566]
* Once inactive message is shown once, don't show it again
* I set it to 30 seconds, but it seems to be appearing much faster
* First message has distorted image

<img width="383" alt="screen shot 2018-03-09 at 11 06 10 am" src="https://user-images.githubusercontent.com/1054674/37225002-0b1cd412-238a-11e8-8125-6f431eb90566.png">

**Comment by gliblozhkovyi** [comment]
I checked at current dev. Set inactive to 1 sec. 
Don't see any issue. Is that still reproducible on your setup? 

http://recordit.co/PtDAsuwwoS
