### ISSUE TITLE
/careers upload

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#571]
Right now the user can upload any file type.  We are only accepting PDF.  Please block all othere file types. 

We should be re-using this Component in other places like the homepage-image upload.   In that case, images are allowed.

When images are allowed, show the preview image (current state).  If the upload is not an image (example: PDF) do not show an image because it becomes a broken image tag.

Right now, files are placed in the root of the bucket.  Let's change the path.

For DEV mode, put files in :
/resumes/dev/YYYY-MM/

For PROD mode, put files in:
/resumes/career_page1/YYYY-MM/

For the filename, let's change the format.  Please keep the user's original filename.  Pre-pend their filename with the email address like this:

`kyle[at]dataskeptic.com_originalfilename.png`

If the SAME user uploads the same filename, their later version would overwrite the earlier version.  This is a feature, not a bug.

**Comment by gleblozhkovoy** [comment]
> We should be re-using this Component in other places like the homepage-image upload. In that case, images are allowed.

Yeah, that what my goal to design that component. A single point to upload/display/manipulate files list.

> When images are allowed, show the preview image (current state). If the upload is not an image (example: PDF) do not show an image because it becomes a broken image tag.

I'm going to extend component and display the file icon with extension format in the case file is not an image.

**Comment by gleblozhkovoy** [comment]
`InvalidBucket: Bucket names cannot contain forward slashes. Bucket: /resumes/dev/2018-03`

**Comment by gleblozhkovoy** [comment]
Now in case of file unsupported preview (In future I think we should add audios) component will show only extension icon 

<img width="495" alt="screen shot 2018-03-13 at 12 33 06 pm" src="https://user-images.githubusercontent.com/20016615/37336643-b645a110-26ba-11e8-99fb-9a33533a58f7.png">
