### ISSUE TITLE
/careers/[CITYNAME]

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#583]
![image](https://user-images.githubusercontent.com/1054674/37318734-659997da-2629-11e8-9479-9e614d590b03.png)

**Comment by kylepolich** [comment]
API will return:
```
{
  "blogs": [{...}, {...}, {...}],
  "events": [{...}, {...}, {...}],
  "jobs": [{...}, {...}, {...}]
}
```

**Comment by gleblozhkovoy** [comment]
Pretty close to finalize 
![screencapture-localhost-3000-careers-city-chicago-2018-03-20-17_00_55](https://user-images.githubusercontent.com/20016615/37662692-48300188-2c60-11e8-8f26-7c8ceff7b023.png)
