### ISSUE TITLE
Fix "here" style to appear as a link

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#594]
<img width="385" alt="screen shot 2018-03-13 at 9 19 31 pm" src="https://user-images.githubusercontent.com/1054674/37383183-4a2ad58c-2704-11e8-8048-bc78cafadc15.png">

**Comment by kylepolich** [comment]
Also here

<img width="284" alt="screen shot 2018-03-13 at 9 21 36 pm" src="https://user-images.githubusercontent.com/1054674/37383213-8baea7d6-2704-11e8-8752-ab457228f9c6.png">

**Comment by gleblozhkovoy** [comment]
Fixed by other commits. Let's close it 

<img width="533" alt="screen shot 2018-03-20 at 1 56 35 pm" src="https://user-images.githubusercontent.com/20016615/37653152-85f6f766-2c46-11e8-8518-46292453c2cd.png">
