### ISSUE TITLE
More attractive error on checkout

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#60]
<img width="586" alt="screen shot 2017-02-27 at 9 29 51 am" src="https://cloud.githubusercontent.com/assets/1054674/23372177/6a0c9120-fccf-11e6-95d3-d3cdfa2faac6.png">

This message is a little hard to read.  Please make it the same as the Red error on the address.  For example, if you leave Last Name blank, it says "Please enter your name".  That error looks good!  Copy the format for the second error section.

**Comment by glozhkovoy** [comment]
I think it closed. Is not?

**Comment by kylepolich** [comment]
Yes, fixed.  Thanks.
