### ISSUE TITLE
Download Area bug

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#600]
In production, we have one item returned by the API.  The S3 object is public:

https://s3.amazonaws.com/dataskeptic.com/members/2018/high-res-ai-art.png

But the redirect:

https://dataskeptic.com/api/v1/download?bucket=dataskeptic.com&path=/members/2018/high-res-ai-art.png

Returns:

```
{
message: "The specified key does not exist.",
code: "NoSuchKey",
region: null,
time: "2018-03-15T01:00:17.694Z",
requestId: "3CBB341064BA95D0",
extendedRequestId: "QoiLk5cnWWV8Qhoh/C+R+ltRrk9HrIcxCD6ajsp0FgUx8FpUf5jNLfIevKOa51OoHqBR35dzS3g=",
statusCode: 404,
retryable: false,
retryDelay: 58.26905461804359
}
```

This is lower priority than Careers page related Issues

**Comment by gleblozhkovoy** [comment]
Notes for myself: file accessible by `https://dataskeptic.com/api/v1/download?bucket=dataskeptic.com&path=members/2018/high-res-ai-art.png`
