### ISSUE TITLE
Email popup

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#604]
Let's add a pop interstitial asking people to join our mailing list as long as they have scrolled down to offset > 10 and been on the page for 5 seconds

**Comment by kylepolich** [comment]
Be careful that this isn't annoying like most annoying sites.

On mobile, make it a short height div at the bottom of the screen, which is sticky to the bottom.

On desktop, put it as a small box in the lower left corner.

In both cases, it should have an easy X button to get rid of it.  If user presses X, save the timestamp in their session.  If the timestamp is present, NEVER show the popup again.  Maybe in the future, we will show again after many weeks, but for now, don't show again if X pressed.

**Comment by gliblozhkovyi** [comment]
Progress so far 

![5hvh9fkm9r](https://user-images.githubusercontent.com/20016615/40480708-fc75aba0-5f57-11e8-9e5e-f9f121014701.gif)

**Comment by gliblozhkovyi** [comment]
- [ ] Mobile Support

**Comment by gliblozhkovyi** [comment]
I took the idea for mobile popups from stripe subscribe popup. I think they choose the best UI/UX solution for mobiles. 

![fmxt9jkpqg](https://user-images.githubusercontent.com/20016615/40639964-725554ca-631c-11e8-8d4e-9b58e6c0cb08.gif)

**Comment by gliblozhkovyi** [comment]
Note that email popup implemented on top of popup framework. So we could reuse that behaviour for other popups in case we'll need them in the future.
