### ISSUE TITLE
Bug on Podcast "View More" link

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#61]
http://g.recordit.co/THu0bd0XvS.gif

The user gets a 404 page on older podcast show notes.

My old site was PHP.  When I started the new site, I made all the old *.php links redirect to new page names.  However, the RSS feed still has the old URLs.  Thus, the `redirects.js` helps redirect these old links to the new locations.

Recently, the links were changed to go to the page, rather than using `<a href="">` and I think this broke the functionality.

If this can be fixed quickly, let's fix it.  If it cannot be fixed quickly, let me know and I will switch it back to using anchor tag while the better fix is being developed.

Better fix is probably to have `BlogListItem.js` use the mapping from `redirects.js` to check for a redirect and then show it directly.

**Comment by glozhkovoy** [comment]
Delivered client-side quick fix https://github.com/data-skeptic/dataskeptic.com/pull/62
