### ISSUE TITLE
Inactive message should only be shown once

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#613]
<img width="407" alt="screen shot 2018-03-21 at 12 11 46 am" src="https://user-images.githubusercontent.com/1054674/37697892-c705968a-2c9c-11e8-8e5d-90f8f7481317.png">

**Comment by kylepolich** [comment]
These all appear very quickly together

**Comment by gliblozhkovyi** [comment]
Couldn't repro it one more time. I set innactive value to 1sec – http://recordit.co/67donWHhXU
