### ISSUE TITLE
Verify "author" in CMS

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#619]
If an Admin user wants to change the blog's Author, then do a validation that the author exists in the contributors cache.

**Comment by kylepolich** [comment]
After #630 is ready, we can remove the text input and replace it with a <select>

**Comment by gliblozhkovyi** [comment]
![ipzoggyg5e](https://user-images.githubusercontent.com/20016615/38134208-ae277eb4-341a-11e8-8c2f-6943772a25dd.gif)
