### ISSUE TITLE
Can't type in "Location" field

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#641]
/admin/job/api

bundle.js:17351 Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.
warning @ bundle.js:17351

**Comment by gliblozhkovyi** [comment]
About the warning – there is no correct solution for `dev` (https://github.com/facebook/draft-js/issues/81), however, it will be not present in `prod` - warnings are ignored. 


Regarding the `location` field (accept only digits). Location is zip-code by the https://github.com/data-skeptic/dataskeptic.com/issues/523
