### ISSUE TITLE
dataskeptic.com/careers/jobs/add

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#645]
Use the same Components from Admin, but this page is public.

Use this API to get ads (only one for now): /dev/store/ads/list

This API is the same as the existing endpoint:/dev/store/products/list

The user can add to cart and checkout.

**Comment by gliblozhkovyi** [comment]
Could you add more information about this one?

**Comment by kylepolich** [comment]
Maybe it was confusing because I accidentally deleted the job ad so the API was empty.  It now returns something like this:

```
{
Count: 1,
  Items: [{
    sku: "sku_CZcnKMfDnPoSIw",
    img: "https://s3.amazonaws.com/dataskeptic.com/img/2018/logo-200.jpg",
    title: "dataskeptic.com job ad",
    price: 199,
    paypal: "",
    active: 1,
    id: 26,
    type: "ad",
    desc: "4 week job ad"
  }]
}
```

We need to have a page where companies can buy a job add.  Let's make the UI found at:

dataskeptic.com/careers/ads/checkout

At this link, the *public* user (not just in admin) can use the same component as we have here:
https://dataskeptic.com/admin/job/add

So reuse those components in this new place, and also, let's set up the Stripe integration so the user can pay for the ad.

**Comment by kylepolich** [comment]
Everything clear?  I want to launch this.

**Comment by gliblozhkovyi** [comment]
Now when real data is ready it’s looks more clear for me. Many thanks for clarification

**Comment by gliblozhkovyi** [comment]
Sneak peak of the advertise field 

<img width="278" alt="screen shot 2018-04-10 at 1 11 09 pm" src="https://user-images.githubusercontent.com/20016615/38550984-a935a0e4-3cc0-11e8-8d8e-fa696c2f3fc9.png">

**Comment by gliblozhkovyi** [comment]
Client UI flow 

![7adabpyxlc](https://user-images.githubusercontent.com/20016615/38568797-453093a6-3cf2-11e8-9e31-0f324e60bb73.gif)

**Comment by gliblozhkovyi** [comment]
I'm blocked on this before we will solve the problem with `No such sku`

**Comment by kylepolich** [comment]
The price should not be changed from the API response.  Current price is set at $199, not $1.99

**Comment by kylepolich** [comment]
Can you hard code (for now) and try this one? `prod_CZcmAcmO2Esd9O`

**Comment by kylepolich** [comment]
What is the issue with `No such sku`?  I just confirmed with Stripe that the correct sku is shwon above.  What are the steps so i can reproduce it?

**Comment by gliblozhkovyi** [comment]
@kylepolich regarding the `no such sku`

Please check this PR https://github.com/data-skeptic/dataskeptic.com/pull/664 to reproduce the issue. Notice that page is located at `careers/job/add`

**Comment by kylepolich** [comment]
@gliblozhkovyi Nothing is there when I check that link.  I have the latest and this is what I get:

![screen shot 2018-04-12 at 3 41 49 pm](https://user-images.githubusercontent.com/1054674/38707850-116e27c8-3e68-11e8-8f93-a7e6fc3de6ba.png)

**Comment by gliblozhkovyi** [comment]
This might happen if you started the app at `dev` and switched to the `careers_job_add` after. That's how webpack works

**Comment by kylepolich** [comment]
@gliblozhkovyi the situation you describe does not apply to me.  I did `git pull` then `npm run dev` and this is the result.  I just tested again.  Please fix.

**Comment by kylepolich** [comment]
@gliblozhkovyi Please address this ASAP.  We need to get this moving and I have not been able to test for some time now.

**Comment by kylepolich** [comment]
Right, as noted, you need to fix the URL.

**Comment by gliblozhkovyi** [comment]
Aha! Finnaly I got the requirements correctly. Thanks for clarification

**Comment by gliblozhkovyi** [comment]
Updated the route path. 

After a deep look, I have fixed the checkout for `ads.` The reason for `no SKU` was `size.`
