### ISSUE TITLE
Add job style

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#649]
Textarea border need to match the border of the other `input`s.  Also, make the height 3 times larger than it is now.

![screen shot 2018-03-29 at 8 37 23 am](https://user-images.githubusercontent.com/1054674/38098328-9d00cfd0-332c-11e8-8d90-e484f9f9956b.png)

Can we remove the icons below?

![screen shot 2018-03-29 at 8 40 13 am](https://user-images.githubusercontent.com/1054674/38098412-de17df2c-332c-11e8-8af8-f0c9e639d70f.png)

**Comment by gliblozhkovyi** [comment]
Sure, we can control buttons set

**Comment by kylepolich** [comment]
@gliblozhkovyi This is not complete.  I see the icons were removed, but it looks like you skipped this comment:

Textarea border need to match the border of the other inputs. Also, make the height 3 times larger than it is now.

By larger, I mean height.

**Comment by gliblozhkovyi** [comment]
Absolutely missed that part. Already delivered at https://github.com/data-skeptic/dataskeptic.com/pull/680
