### ISSUE TITLE
Remember last mp3 being played and position

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#650]
Use the cookie or session to remember what the user is listening to and what their approximate last position was.  If they leave the site and come back later, retrieve the MP3 URL and position.  Update the state so that the player appears immediately with the file loaded and correct position.

While you're at it, we should probably save the volume setting too, but position and url are critical.

**Comment by gliblozhkovyi** [comment]
Please check that it works as expected. Now, site memorizes mp3 and position, volume and play state (I'm not sure it's a good choice - we could change it in future).

**Comment by gliblozhkovyi** [comment]
I have a nice and simple idea! Actually, that feature is working amazingly in production. 

Do you know that youtube has a similar feature for videos called "Watch again" or "Continue to watch", I guess. The thing is that youtube restore the video not on current position, but a few seconds before that. Maybe it's some sort of human psychology - we remember that 5 seconds and could remember what was before an entire video. 

Maybe we could follow that idea end restore the position at 5 secs before. 

What do you think, @kylepolich

**Comment by kylepolich** [comment]
@gliblozhkovyi Awesome idea!  Let's do it!!!
