### ISSUE TITLE
Switch backend of /podcast page

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#651]
Currently, the /podcast page reads data from the cache.  The cache takes it from the XML / RSS feed.  I want to move to a more database driven version where the website does not need to know about the RSS file.

I created this new endpoint:

`/podcast/episodes/list?limit=10&offset=0`

We will also need this to support infinite scroll.

In time, we will make the infinite scroll very fancy.  As the user scrolls down, we can animate the guest circle heads in and out, have their bios animate by in parallax, show related content, etc. Very interactive.  This is for the future, not for this Issue.

For this issue, let's switch over to using this new API feed and switch to infinite scroll.  Other than that, it should be functionally similar to the current /podcast page.

As we move to infinite scroll, please have the Years selector update.  Do we need to REMOVE the ability to click the years?  Otherwise how would you know the offset?

**Comment by gliblozhkovyi** [comment]
1. I expect to have `total` in response to ensure ability load more 

> Do we need to REMOVE the ability to click the years? 
2. No, we shouldn't in case API process `year` attribute with `limit/offset` correctly 

3. Otherwise, how would you know the offset?
Offset means currently loaded list length? So after autoload (first load) we probably could determinate that value

**Comment by gliblozhkovyi** [comment]
@kylepolich `podcast/episodes/list?limit=10&offset=0` start response with error message such as `request is not defined`

**Comment by gliblozhkovyi** [comment]
Nice. It works. 

Could response be improved to use this format?
```{list: [...], total: N}```
