### ISSUE TITLE
Fix critical production error

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#653]
PDF uploading is totally broken.

When you upload one time, nothing happens.  If you try again it says "The specified key does not exist."

**Comment by gliblozhkovyi** [comment]
I have debugged the flow. Seems like it's broken at `drip/user/add` request. 

Is lambda still exist? 

Request example `/dev/drip/user/add` 

```{ "tag_id": 1, "email": "lozhkovoygleb[At]icloud.com" }```

**Comment by gliblozhkovyi** [comment]
Now the user will see `lambda error message` + `human readable message`. Like this one.

<img width="574" alt="screen shot 2018-04-02 at 11 55 04 am" src="https://user-images.githubusercontent.com/20016615/38190438-deebd460-366c-11e8-9c5e-e155f4c89078.png">

**Comment by gliblozhkovyi** [comment]
However, that doesn't fix the fact `register user` endpoint a.k.a. `dev/drip/user/add` isn't exist. Is the URL changed?

**Comment by kylepolich** [comment]
The user needs to get a good error NO MATTER WHAT.  We have to do much better error and exception handling.  I restore this API call, but still the production system is not working.

**Comment by gliblozhkovyi** [comment]
Yeah. The main reason why the error was missed – previously I expect the error message from the response of working lambda (incorrect data, something happened, e.t.c) and we never have a case like that. In future, I will follow current solutions for lambdas as well.
