### ISSUE TITLE
Resolve rollbar issues

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#661]

**Comment by kylepolich** [comment]
@gliblozhkovyi we have made great progress in recent updates here.  Previously, our free Rollback was hitting the quota on the first day!  Now, it is day 10 and I am getting Rollbar alerts.  This is a huge improvement!  Let's keep going.

**Comment by gliblozhkovyi** [comment]
@kylepolich Please, let's try to merge the https://github.com/data-skeptic/dataskeptic.com/pull/702 PR. I think it will help resolve a lot of issues
