### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#667]
Somewhere, something is linking to us with a bad url for valid content like below

Site error: {"details":"/blog//bonus/2018/ai-at-microsoft","msg":"404!"}

Notice two //.  It's probably our fault.  Somewhere we generated it by mistake, I bet.  Or maybe some random person made a bad link on their site.  I don't know!

I think we can fix this.  Can you add something to the redirect like:

`path = path.replaceAll("//", "/")`

I know that `replace` only does ones and javascript lacks `replaceAll` but I think there is a nice template for it somewhere.

**Comment by gliblozhkovyi** [comment]
However, double checked all links on dataskeptic and they looks ok

**Comment by kylepolich** [comment]
Yes, it might not be our error, but it exists and we should be able to correct it to redirect on the server.  Please implement the fix described.

**Comment by gliblozhkovyi** [comment]
Yes. We could handle incorrect user input cases as well. Got it. Simple redirect
