### ISSUE TITLE
Dev is broken

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#675]
The current `dev` branch does not work for `/podcasts`.  Start the site, click on "podcasts" and you get this error.

<img width="1245" alt="screen shot 2018-04-20 at 11 08 46 am" src="https://user-images.githubusercontent.com/1054674/39066799-3e2d51c0-448b-11e8-8022-c0b1299cfd63.png">

**Comment by gliblozhkovyi** [comment]
<img width="709" alt="screen shot 2018-04-20 at 9 22 17 pm" src="https://user-images.githubusercontent.com/20016615/39067414-36a237f8-44e1-11e8-8387-14cb4b025274.png">

Couldn't reproduce that issue (error from ads blocker extension). Maybe it was some time gap when `dev` database was filled with new episode item. However, this PR (https://github.com/data-skeptic/dataskeptic.com/pull/678) should cover (in idea) that case. That should not be present at `prod`
