### ISSUE TITLE
Bug: dates are wrong on blog

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#68]
<img width="265" alt="screen shot 2017-02-27 at 11 49 22 pm" src="https://cloud.githubusercontent.com/assets/1054674/23396201/737ac9a2-fd47-11e6-8b05-f75782cc6539.png">

These are the wrong dates, and it allows 0 for day of month.

**Comment by glozhkovoy** [comment]
"Weapons of Math Destruction" has last_rendered": "2017-02-24", and "publish_date" on "2017-02-25"

**Comment by glozhkovoy** [comment]
Fixed https://github.com/data-skeptic/dataskeptic.com/pull/71
