### ISSUE TITLE
User should be able to close player while loading

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#682]
The "X" button should not be disabled ever.

<img width="352" alt="screen shot 2018-04-20 at 4 14 04 pm" src="https://user-images.githubusercontent.com/1054674/39077348-0556694c-44b6-11e8-88a6-1cf9caafc153.png">

Can we move away from this design entirely?  It looks awkward.  If the file cannot be played, let's have the Play button be disabled and have a spinner inside it, but the entire bar does not need to be disabled, especially when other elements like the title can be known immediately.

**Comment by gliblozhkovyi** [comment]
Following your needs, updated the loading animation: removed loading bar and disabled volume/track sliders, spinner in play button

![aztxogxbop](https://user-images.githubusercontent.com/20016615/39189246-7528c414-47da-11e8-9984-087cd0a6070d.gif)

**Comment by kylepolich** [comment]
Looking really good!  Great improvements!!!  I will wait for PR to be ready and then deploy.
