### ISSUE TITLE
/podcast Years is not working

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#686]

**Comment by gliblozhkovyi** [comment]
@kylepolich `total` attribute ignore `year` value

**Comment by kylepolich** [comment]
@gliblozhkovyi I will fix the api, but there is still work to be done on the front end for this Issue

**Comment by gliblozhkovyi** [comment]
I have merged with current dev. Please check how it works.

Demo video => http://recordit.co/5yfTdDsSrR

What else is left?
