### ISSUE TITLE
Player breaks https

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#700]
To reproduce:

* Go to site.
* Play current episode (Winograd Schema Challenge)
* Notice https goes to http because the image is the wrong protocol.

To fix it, the player needs to check the link and force it to https if it is http.

**Comment by gliblozhkovyi** [comment]
We have the same `http=>https` logic for cached episodes. Now we are moving to the lambda's backend and need to be careful with that cases. 

I expect could happen for blogs.

However, this PR https://github.com/data-skeptic/dataskeptic.com/pull/701 fix that logic for episodes page and player in all cases.

**Comment by gliblozhkovyi** [comment]
Note that I have created the PR for `master` to fix critical issue in the player ASAP.
