### ISSUE TITLE
Production mode styles error

### ISSUE THREAD

**Issue by glozhkovoy** [data-skeptic/dataskeptic.com#85]
It seems like styles doesn't compressed in to the bundle in production mode. 

After page loading server takes time to build main styles file.

![jcosxinruj](https://cloud.githubusercontent.com/assets/20016615/23820797/135048c8-0629-11e7-99b4-a322993ae73a.gif)

**Comment by kylepolich** [comment]
Yes, good catch.  A fix will be a nice improvement.

**Comment by kylepolich** [comment]
Fixed.  Thanks!
