### ISSUE TITLE
Send email notifications on audio upload

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#89]
Create an AWS Lambda function triggered by an upload to the `dataskeptic-recordings` bucket.  When an upload is complete, it should use SES to send an email to kyle@dataskeptic.com with a full URL link to the audio file in the bucket.  The metadata related to the recording (such as the user's name) should all be included in the email.

More details on the metadata in a different Issue.

**Comment by glozhkovoy** [comment]
Here we are https://github.com/data-skeptic/dataskeptic.com/pull/100/commits/484076e7d53e05a359cdf9cf0301c4130d21ecfb
