### ISSUE TITLE
Recording sample rate is slightly off

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#91]
My recordings sound like the pitch is a little higher than it should be.  I think the samples per second might be off.  Either it was recorded wrong or the file metadata has it listed at a slightly faster sampling that is should.  The value is very close, but a little off.

**Comment by glozhkovoy** [comment]
Fixed in https://github.com/data-skeptic/dataskeptic.com/pull/100/commits/4ebc7e0100416524799bad6ce0500ad9f76e4a4f
