### ISSUE TITLE
Workflow on audio recording

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#92]
When the user clicks the record button, an interstitial pop up should appear.

FIRST STAGE
The first screen should have a short explanation and a "Start Recording" button.  Text should be: "Recording will start when you hit the button below.  You will have a chance to review your recording before submitting."

SECOND STAGE
Show a counter of how much time has passed.  Show the AudioIndicator component.  Repeat the question text in this panel so the user is reminded what question they are answering.  A "Stop" button should be shown.  If the user closes the browser prematurely, the server should upload the partial audio.

THIRD STAGE
Provide a play button so the user can review the recording.  There are two buttons.  "Discard and record again" (go to second stage) and "Ready to submit" (go to fourth stage)

FOURTH STAGE
Two input boxes.  "Your name" and "email address".  Put validation on email but not on name.  A button says "submit".  When submit is clicked, start the upload.  The button should become disabled and show a waiting logo.  If the user closes the browser, the upload should continue regardless.  When the upload completes, go to fifth stage

FIFTH STAGE
A heading that says "Thank you for your input".  Text reads "If you have anything you'd like to add or follow up on, feel free to reach out to kyle@dataskeptic.com directly".  Lastly, a button that says "Close" removes the interstitial.

Metadata to capture: Username and email (given by the user in input fields), IP address, and User agent string.

**Comment by glozhkovoy** [comment]
Full flow delivered in https://github.com/data-skeptic/dataskeptic.com/pull/100/commits/012628f6ff4db271ea20b781aa9a63f16bbf2db4
